### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by rightevil** [Jasmine969/WechatVisualization#6]
after i analyse three times, it show this error.
```
>python main.py
开始分词
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\30969\AppData\Local\Temp\jieba.cache
Loading model cost 0.407 seconds.
Prefix dict has been built successfully.
  0%|                                                                                            | 0/3 [00:00<?, ?it/s]F:\wechat_visulization\WechatVisualization-master\WechatVisualization-master\parse.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[, 呲, 牙, ]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  records.loc[i, 'keywords'] = ', '.join(result)
F:\wechat_visulization\WechatVisualization-master\WechatVisualization-master\parse.py:74: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  records.loc[i, 'emoji'] = ', '.join(emoji_res)
100%|███████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 998.96it/s]
F:\wechat_visulization\WechatVisualization-master\WechatVisualization-master\parse.py:82: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  records.replace('', float('nan'), inplace=True)  # 方便后面dropna
====================
计算词频并制作词云
====================
计算word_specificity
word_min_count应不超过1
top_k应不超过3
====================
计算emoji_specificity
emoji_min_count应不超过2
top_k应不超过1
Traceback (most recent call last):
  File "F:\wechat_visulization\WechatVisualization-master\WechatVisualization-master\main.py", line 41, in <module>
    main(
  File "F:\wechat_visulization\WechatVisualization-master\WechatVisualization-master\main.py", line 31, in main
    emoji_specificity(name1, name2, **p_emoji_specificity)
  File "F:\wechat_visulization\WechatVisualization-master\WechatVisualization-master\emoji_specificity.py", line 33, in emoji_specificity
    plt.yticks(y, all_df.iloc[:top_k, 0].tolist())
  File "D:\py\lib\site-packages\matplotlib\pyplot.py", line 2139, in yticks
    labels_out = ax.set_yticklabels(labels, minor=minor, **kwargs)
  File "D:\py\lib\site-packages\matplotlib\axes\_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
  File "D:\py\lib\site-packages\matplotlib\_api\deprecation.py", line 297, in wrapper
    return func(*args, **kwargs)
  File "D:\py\lib\site-packages\matplotlib\axis.py", line 2025, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (3), usually from a call to set_ticks, does not match the number of labels (1).
```
and it seems have bug? the date seems just one day?
```
时域处理
第一天：2021-06-03
最后一天：2021-06-03
共计1天
```
maybe it wasnot error,but when i check the html and png, it seems dont have lots of data.

**Comment by rightevil** [comment]
sorry, i dont set msg.csv rightly.

**Comment by rightevil** [comment]
it already fixed after i set msg.csv rightly, sorry for my rush
